"""Agrega estaso 'EN_CURSO' a retorno

Revision ID: 073dfca8eded
Revises: dc6ab2fc7af5
Create Date: 2026-05-06 15:22:34.903188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073dfca8eded'
down_revision: Union[str, Sequence[str], None] = 'adebc859019a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
