"""Modelo cargar contenido multimedia

Revision ID: 84d88db3619a
Revises: dc6ab2fc7af5
Create Date: 2026-04-30 03:33:32.655904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d88db3619a'
down_revision: Union[str, Sequence[str], None] = 'dc6ab2fc7af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedia',
    sa.Column('mm_codigo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('re_codigo', sa.Integer(), nullable=False),
    sa.Column('mm_tipo', sa.String(length=10), nullable=False),
    sa.Column('mm_url', sa.String(length=500), nullable=False),
    sa.Column('mm_nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('mm_fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['re_codigo'], ['retorno.codigo'], ),
    sa.PrimaryKeyConstraint('mm_codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multimedia')
    # ### end Alembic commands ###
