"""tabla registro_retorno

Revision ID: a0b72de79d50
Revises: efee06555c1c
Create Date: 2026-05-03 04:39:38.803770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b72de79d50'
down_revision: Union[str, Sequence[str], None] = 'efee06555c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_retorno',
    sa.Column('reg_codigo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('us_codigo', sa.Integer(), nullable=False),
    sa.Column('re_codigo', sa.Integer(), nullable=False),
    sa.Column('reg_num_hospedaje', sa.Integer(), nullable=False),
    sa.Column('reg_num_transporte', sa.Integer(), nullable=False),
    sa.Column('reg_num_parqueadero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['re_codigo'], ['retorno.codigo'], ),
    sa.ForeignKeyConstraint(['us_codigo'], ['usuario.us_codigo'], ),
    sa.PrimaryKeyConstraint('reg_codigo'),
    sa.UniqueConstraint('us_codigo', 're_codigo', name='uk1_uk2_registro_retorno')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_retorno')
    # ### end Alembic commands ###
