"""Tabla persona_grupo_retorno

Revision ID: f1ab986c6e4d
Revises: 1c61b63e302b
Create Date: 2026-04-29 05:52:14.583557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ab986c6e4d'
down_revision: Union[str, Sequence[str], None] = '1c61b63e302b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
