"""Agrega tablas publicacion y multimedia

Revision ID: f34c444c4f8e
Revises: 073dfca8eded
Create Date: 2026-05-11 03:25:15.211242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34c444c4f8e'
down_revision: Union[str, Sequence[str], None] = '073dfca8eded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacion',
    sa.Column('pu_codigo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('re_codigo', sa.Integer(), nullable=False),
    sa.Column('us_codigo_autor', sa.Integer(), nullable=False),
    sa.Column('pu_resena', sa.String(length=1000), nullable=True),
    sa.Column('pu_titulo', sa.String(length=255), nullable=False),
    sa.Column('pu_fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['re_codigo'], ['retorno.codigo'], ),
    sa.ForeignKeyConstraint(['us_codigo_autor'], ['usuario.us_codigo'], ),
    sa.PrimaryKeyConstraint('pu_codigo')
    )
    op.create_table('multimedia',
    sa.Column('mu_codigo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pu_codigo', sa.Integer(), nullable=False),
    sa.Column('mu_tipo', sa.Enum('IMAGEN', 'VIDEO', 'DOCUMENTO', name='tipomultimedia'), nullable=False),
    sa.Column('mu_formato', sa.Enum('JPG', 'JPEG', 'PNG', 'GIF', 'MP4', 'AVI', 'MOV', 'MKV', 'PDF', 'EMBED', name='formatomultimedia'), nullable=False),
    sa.Column('mu_url', sa.String(length=500), nullable=False),
    sa.Column('mu_descripcion', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['pu_codigo'], ['publicacion.pu_codigo'], ),
    sa.PrimaryKeyConstraint('mu_codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multimedia')
    op.drop_table('publicacion')
    # ### end Alembic commands ###
